# fly.toml app configuration file generated for godot-game-server-pool on 2024-01-08T14:19:54+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "godot-game-server-pool"
primary_region = "nrt"

[build]

[env]
PORT = "5000"

[[services]]
protocol = "udp"
internal_port = 5000

[[services.ports]]
port = 5000

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
